In [1]:
import pandas as pd
import numpy as np
import joblib

In [2]:
best_model = joblib.load("../models/best_model.pkl")

print("Best model loaded successfully!")

Best model loaded successfully!

In [3]:
df_priority = pd.read_csv("../results/patient_predictions.csv")

df_priority.head()

,age,gender,admission_type_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses,insulin,change,diabetesMed,Actual_Readmission,Readmission_Probability
0,[80-90),Male,1,7,10,55,1,31,0,0,0,8,Steady,No,Yes,0,0.524772
1,[70-80),Female,2,4,2,47,0,12,0,0,0,8,No,No,No,0,0.389444
2,[60-70),Female,1,7,6,87,0,18,0,0,0,9,Steady,Ch,Yes,0,0.475936
3,[70-80),Female,1,7,6,27,0,16,0,0,0,8,Steady,No,Yes,0,0.494335
4,[50-60),Male,2,2,1,44,1,15,0,0,0,9,Steady,No,Yes,0,0.462590

In [4]:
def assign_priority(probability):
    if probability >= 0.70:
        return "High"
    elif probability >= 0.40:
        return "Medium"
    else:
        return "Low"

In [5]:
df_priority["Followup_Priority"] = df_priority[
    "Readmission_Probability"
].apply(assign_priority)

df_priority.head()

,age,gender,admission_type_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses,insulin,change,diabetesMed,Actual_Readmission,Readmission_Probability,Followup_Priority
0,[80-90),Male,1,7,10,55,1,31,0,0,0,8,Steady,No,Yes,0,0.524772,Medium
1,[70-80),Female,2,4,2,47,0,12,0,0,0,8,No,No,No,0,0.389444,Low
2,[60-70),Female,1,7,6,87,0,18,0,0,0,9,Steady,Ch,Yes,0,0.475936,Medium
3,[70-80),Female,1,7,6,27,0,16,0,0,0,8,Steady,No,Yes,0,0.494335,Medium
4,[50-60),Male,2,2,1,44,1,15,0,0,0,9,Steady,No,Yes,0,0.462590,Medium

In [6]:
priority_counts = df_priority["Followup_Priority"].value_counts()

print(priority_counts)

print(
    df_priority["Followup_Priority"]
    .value_counts(normalize=True) * 100
)

Followup_Priority
Medium    16024
Low        4003
High        126
Name: count, dtype: int64
Followup_Priority
Medium    79.511735
Low       19.863048
High       0.625217
Name: proportion, dtype: float64

In [7]:
df_priority.to_csv(
    "../results/patient_priority_results.csv",
    index=False
)

print("Priority classification results saved successfully!")

Priority classification results saved successfully!

In [8]:
df_priority.insert(
    0,
    "Patient_ID",
    ["P" + str(i).zfill(5) for i in range(1, len(df_priority) + 1)]
)

df_priority.head()

,Patient_ID,age,gender,admission_type_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses,insulin,change,diabetesMed,Actual_Readmission,Readmission_Probability,Followup_Priority
0,P00001,[80-90),Male,1,7,10,55,1,31,0,0,0,8,Steady,No,Yes,0,0.524772,Medium
1,P00002,[70-80),Female,2,4,2,47,0,12,0,0,0,8,No,No,No,0,0.389444,Low
2,P00003,[60-70),Female,1,7,6,87,0,18,0,0,0,9,Steady,Ch,Yes,0,0.475936,Medium
3,P00004,[70-80),Female,1,7,6,27,0,16,0,0,0,8,Steady,No,Yes,0,0.494335,Medium
4,P00005,[50-60),Male,2,2,1,44,1,15,0,0,0,9,Steady,No,Yes,0,0.462590,Medium

In [9]:
df_priority.to_csv(
    "../results/patient_priority_results.csv",
    index=False
)

print("Final patient priority results saved successfully!")

Final patient priority results saved successfully!